# Generated by Django 4.2.2 on 2024-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_app', '0002_playlist_playlistsong_song_delete_music_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
